# Server props
server:
  port: 8092


# Spring props
spring:             
  datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12347916?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&createDatabaseIfNotExist=true
    username: sql12347916
    password: enHwH6nnDB
    hikari:
      minimumIdle: 5
      maximumPoolSize: 15
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      id:
        new_generator_mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

#       ddl-auto: update


# JWT props     
webapp:
  auth:
    tokenSecret: 926D96C90030DTHEBASICYA581BDBBC
    tokenExpirationMsec: 86400000
    
    
    
# aws
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: HEMANTDEMOKEY
  secretKey: YESITSDUMMY
  bucketName: www.hemantdemo.com